# Podfile for BarqNet iOS

platform :ios, '15.0'
use_frameworks!

# Main app target
target 'WorkVPN' do
  # OpenVPN library for real VPN functionality - using latest stable version
  pod 'OpenVPNAdapter', :git => 'https://github.com/ss-abramchuk/OpenVPNAdapter.git', :branch => 'master'
end

# Network Extension target
target 'WorkVPNTunnelExtension' do
  # OpenVPN library (required in extension too) - using latest stable version
  pod 'OpenVPNAdapter', :git => 'https://github.com/ss-abramchuk/OpenVPNAdapter.git', :branch => 'master'
end

# Post install hooks
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
